# UX Digest

> Generated by `.claude/scripts/ux_digest_gen.py` (usually via `/agi-promote`).
> Do not edit directly. Update the source UX docs and re-promote.

## At-a-glance

### Primary UX docs (paths)

```text
- docs/ux/UX_CONTRACT.md
- docs/ux/UX_SPEC.md
- docs/ux/IA_MAP.md
- docs/ux/UI_STATES.md
- docs/ux/COPY.md
- docs/ux/DESIGN_SYSTEM.md
- docs/ux/UX_REPORT.md
```

## Non-negotiables

### UX_CONTRACT > Non-negotiables

```text
### User Experience
1. **Mobile-first responsive**: All flows functional on 375px+ viewports
2. **Progress visibility**: Upload and processing always show status
3. **Error recovery**: Every error state provides actionable next steps
4. **Korean localization**: Complete Korean UI copy for all user-facing text
5. **WCAG 2.1 AA**: Core flows accessible (focus management, color contrast, labels)

### Privacy and Trust
6. **Private by default**: Videos and reports are private until user explicitly shares
7. **AI disclaimer**: Every report displays disclaimer about AI limitations
8. **Transparent processing**: Clear indication of what AI is analyzing

### Performance
9. **Page load under 2 seconds**: Initial load and navigation
10. **Report load under 1.5 seconds**: Analysis report rendering
11. **Touch targets minimum 48x48px**: All interactive elements

---
```

## Screens & routes

### UX_SPEC > Screens & routes

```text
### Route Table

| Route | Screen | Auth Required | SEO |
|-------|--------|---------------|-----|
| `/` | Landing Page | No | Yes |
| `/login` | Login Options | No | No |
| `/auth/callback/kakao` | OAuth Callback | No | No |
| `/auth/callback/google` | OAuth Callback | No | No |
| `/dashboard` | Report Dashboard | Yes | No |
| `/upload` | Video Upload | Yes | No |
| `/upload/{upload_id}/select` | Subject Selection | Yes | No |
| `/upload/{upload_id}/specs` | Body Specification | Yes | No |
| `/upload/{upload_id}/processing` | Processing Status | Yes | No |
| `/dashboard/report/{report_id}` | Report View (Owner) | Yes | No |
| `/report/{share_hash}` | Report View (Public) | No | Yes |
| `/404` | Not Found | No | No |
| `/error` | Error Page | No | No |

### Screen Specifications

#### Landing Page (`/`)
| Element | Specification |
|---------|---------------|
| Hero Section | Product value proposition, hero image/animation |
| CTA | "Get Started" / "시작하기" primary button |
| Features | 3 key benefits with icons |
| Footer | Links to privacy policy, terms |

#### Login Options (`/login`)
| Element | Specification |
|---------|---------------|
| Headline | "Welcome to PunchAnalytics" / "PunchAnalytics에 오신 것을 환영합니다" |
| Kakao Button | Yellow (#FEE500), Kakao logo, "Login with Kakao" / "카카오로 로그인" |
| Google Button | White with outline, Google logo, "Login with Google" / "Google로 로그인" |
| Divider | "or" / "또는" between options |
| Legal | Privacy policy link, terms link |

#### Dashboard (`/dashboard`)
| Element | Specification |
|---------|---------------|
| App Bar | Logo, profile menu (avatar, logout) |
| FAB | "Upload Video" floating action button (mobile) |
| Primary Button | "Upload Video" (desktop) |
| Report List | Cards with thumbnail, date, summary

…(truncated)…
```

### IA_MAP > Routes

```text
### Public Routes

| Route | Component | Purpose | SEO | Cache |
|-------|-----------|---------|-----|-------|
| `/` | LandingPage | Product introduction, conversion | Yes | Static, 1 hour |
| `/login` | LoginPage | Authentication options | No | No cache |
| `/auth/callback/kakao` | OAuthCallback | Process Kakao OAuth | No | No cache |
| `/auth/callback/google` | OAuthCallback | Process Google OAuth | No | No cache |
| `/report/{hash}` | SharedReportView | Public report viewing | Yes | Dynamic, 5 min |
| `/404` | NotFoundPage | 404 error handling | No | Static |
| `/error` | ErrorPage | Generic error display | No | No cache |

### Authenticated Routes

| Route | Component | Purpose | Guard |
|-------|-----------|---------|-------|
| `/dashboard` | DashboardPage | Report history, upload CTA | AuthGuard |
| `/dashboard/report/{id}` | ReportDetailPage | Full report with owner actions | AuthGuard + OwnerGuard |
| `/upload` | UploadPage | Video file selection | AuthGuard |
| `/upload/{id}/select` | SubjectSelectPage | Subject identification | AuthGuard + UploadGuard |
| `/upload/{id}/specs` | BodySpecPage | User attributes form | AuthGuard + UploadGuard |
| `/upload/{id}/processing` | ProcessingPage | Analysis status tracking | AuthGuard + UploadGuard |

### Route Parameters

| Parameter | Type | Validation | Example |
|-----------|------|------------|---------|
| `{hash}` | String | 8-character alphanumeric | `abc12def` |
| `{id}` | UUID | UUID v4 format | `550e8400-e29b-41d4-a716-446655440000` |

### Route Guards

| Guard | Behavior | Redirect |
|-------|----------|----------|
| AuthGuard | Check valid session | `/login?redirect={current}` |
| OwnerGuard | Check report ownership | `/dashboard` with error toast |
| UploadGuard | Check upload exists and b

…(truncated)…
```

## Components

### UX_SPEC > Components

```text
### Custom Components (Beyond M3 Baseline)

#### Video Drop Zone
| Property | Value |
|----------|-------|
| Height | 200px (mobile), 300px (desktop) |
| Border | 2px dashed `colors.outline`, 12px radius |
| Icon | `cloud_upload`, 48px |
| Hover State | Border solid, background 4% primary |
| Active State | Border primary, background 8% primary |

#### Subject Thumbnail
| Property | Value |
|----------|-------|
| Size | 100px x 100px (mobile), 150px x 150px (desktop) |
| Border Radius | 8px |
| Selection Ring | 3px solid primary, 4px offset |
| Checkmark | 24px badge, top-right corner |

#### Metric Card
| Property | Value |
|----------|-------|
| Layout | Value top (Display Small), label bottom (Body Small) |
| Left Border | 4px, color based on positive/negative |
| Padding | 16px |
| Background | Surface variant |

#### Timestamp Card
| Property | Value |
|----------|-------|
| Layout | Thumbnail left, text right |
| Thumbnail | 64px x 64px |
| Title | Action type (Title Small) |
| Subtitle | Timestamp "0:34" (Body Small) |
| Height | 80px |

#### Processing Step Indicator
| Property | Value |
|----------|-------|
| Layout | Vertical stepper |
| Active Step | Primary color, filled circle |
| Completed Step | Primary color, checkmark |
| Pending Step | Outline variant, empty circle |
| Connector | 2px line, outline variant (completed: primary) |

### Component States Reference

All components follow the state specifications in UI_STATES.md:
- Loading: Skeleton variants defined
- Empty: Empty state messaging defined
- Error: Inline and page-level error variants
- Validation: Form field error states
- Success: Confirmation feedback

---
```

### DESIGN_SYSTEM > Components

```text
### Buttons

#### Primary Button (Filled)
| Property | Value |
|----------|-------|
| Background | `colors.primary` |
| Text | `colors.onPrimary` |
| Height | 40px |
| Padding | 24px horizontal |
| Border Radius | `radius.full` (20px) |
| Font | Label Large |
| States | Hover: +8% tint, Pressed: +12% tint, Disabled: 38% opacity |

#### Secondary Button (Outlined)
| Property | Value |
|----------|-------|
| Background | Transparent |
| Border | 1px `colors.outline` |
| Text | `colors.primary` |
| Height | 40px |
| States | Hover: 8% primary overlay |

#### Text Button
| Property | Value |
|----------|-------|
| Background | Transparent |
| Text | `colors.primary` |
| Padding | 12px horizontal |
| States | Hover: 8% primary overlay |

### Cards

#### Elevated Card
| Property | Value |
|----------|-------|
| Background | `colors.surface` |
| Elevation | Level 1 (1dp shadow) |
| Border Radius | `radius.medium` (12px) |
| Padding | 16px |

#### Filled Card
| Property | Value |
|----------|-------|
| Background | `colors.surfaceVariant` |
| Elevation | None |
| Border Radius | `radius.medium` (12px) |
| Padding | 16px |

### Form Fields

#### Text Input
| Property | Value |
|----------|-------|
| Height | 56px |
| Background | `colors.surfaceVariant` |
| Border Radius | `radius.small` (4px) top only |
| Border Bottom | 1px `colors.outline` |
| Label | Label Small, positioned above |
| Focus | 2px bottom border `colors.primary` |
| Error | Border `colors.error`, helper text red |

#### Dropdown/Select
| Property | Value |
|----------|-------|
| Height | 56px |
| Background | `colors.surfaceVariant` |
| Icon | Trailing chevron |
| Menu | Elevated surface, max 5 visible items |

### Navigation

#### Top App Bar
| Property | Value |
|----------|-------|
| Heig

…(truncated)…
```

## UI states

### UX_SPEC > UI states

```text
Reference: `docs/ux/UI_STATES.md`

### State Summary by Screen

| Screen | Loading | Empty | Error | Validation | Success |
|--------|---------|-------|-------|------------|---------|
| Landing | Page skeleton | N/A | Server error | N/A | N/A |
| Login | OAuth redirect spinner | N/A | OAuth error | N/A | Redirect |
| Dashboard | List skeleton | No reports | Load error | N/A | N/A |
| Upload | Upload progress | N/A | File/network error | File validation | Upload complete |
| Subject Select | Thumbnail skeleton | No subjects | Extraction error | N/A | Selection confirmed |
| Body Spec | N/A | N/A | Submit error | Field validation | Analysis started |
| Processing | Progress indicator | N/A | Analysis error | N/A | Complete |
| Report | Section skeletons | N/A | Load error | N/A | N/A |

---
```

### UI_STATES > Loading

```text
### Global Loading States

#### Page Load Skeleton
| Property | Specification |
|----------|---------------|
| Background | `colors.surfaceVariant` with 50% opacity pulse animation |
| Animation | Pulse: 0.5s ease-in-out infinite alternate (opacity 0.5 to 1.0) |
| Duration | Display until content ready, minimum 200ms to prevent flash |
| Shape | Match content block shapes (rectangles for text, squares for images) |

#### Inline Spinner
| Property | Specification |
|----------|---------------|
| Component | Circular progress indicator |
| Size | 24px (inline), 48px (centered) |
| Color | `colors.primary` |
| Usage | Button loading states, small async operations |

### Upload Loading States

#### US-002: Video Upload Progress
| State | Visual | Behavior |
|-------|--------|----------|
| Preparing | "Preparing upload..." with spinner | Show immediately on file selection |
| Uploading | Linear progress bar with percentage | Update every 500ms; show bytes transferred |
| Paused | Progress bar paused state, "Upload paused" text | Amber indicator; show resume button |
| Resuming | "Resuming upload..." with spinner | Transition to uploading state |
| Finalizing | "Finalizing..." with indeterminate progress | Show after 100% while server processes |

```
Upload Progress Card:
+------------------------------------------+
|  [video-icon] video_filename.mp4         |
|  [=========>--------------------] 45%    |
|  225 MB / 500 MB • 2 min remaining       |
|  [Cancel]                                |
+------------------------------------------+
```

#### US-003: Thumbnail Generation
| State | Visual | Behavior |
|-------|--------|----------|
| Extracting | "Extracting frames..." with spinner | Show during frame extraction |
| Processing | Grid with skeleton items

…(truncated)…
```

### UI_STATES > Empty

```text
### Dashboard Empty State (US-010)
| Element | Content |
|---------|---------|
| Illustration | Boxing gloves illustration (Material style, outlined) |
| Headline | "No analysis reports yet" |
| Korean | "아직 분석 리포트가 없습니다" |
| Body | "Upload your first sparring video to get AI-powered coaching feedback" |
| Korean Body | "첫 번째 스파링 영상을 업로드하고 AI 코칭 피드백을 받아보세요" |
| CTA Button | "Upload Video" / "영상 업로드" |

```
+------------------------------------------+
|          [boxing-gloves-icon]            |
|                                          |
|     No analysis reports yet              |
|                                          |
|  Upload your first sparring video to     |
|  get AI-powered coaching feedback        |
|                                          |
|         [Upload Video]                   |
+------------------------------------------+
```

### Subject Selection Empty State (US-003)
| Element | Content |
|---------|---------|
| Scenario | No people detected in video frames |
| Headline | "No subjects detected" |
| Korean | "분석 대상을 찾을 수 없습니다" |
| Body | "We couldn't identify any people in your video. Please upload a video with clear visibility of the subjects." |
| Korean Body | "영상에서 사람을 식별할 수 없습니다. 대상이 잘 보이는 영상을 다시 업로드해 주세요." |
| CTA Button | "Upload Different Video" / "다른 영상 업로드" |

### Search Results Empty State (Future: Report Search)
| Element | Content |
|---------|---------|
| Headline | "No reports found" |
| Korean | "검색 결과가 없습니다" |
| Body | "Try adjusting your search or filters" |
| Korean Body | "검색어나 필터를 조정해 보세요" |

---
```

### UI_STATES > Error

```text
### Network Errors

#### Connection Lost
| Element | Content |
|---------|---------|
| Icon | `cloud_off` (Material Symbol) |
| Headline | "Connection lost" |
| Korean | "연결이 끊어졌습니다" |
| Body | "Check your internet connection and try again" |
| Korean Body | "인터넷 연결을 확인하고 다시 시도해 주세요" |
| Primary Action | "Retry" / "다시 시도" |
| Secondary Action | "Go Offline" (if applicable) |

#### Server Error (5xx)
| Element | Content |
|---------|---------|
| Icon | `error_outline` (Material Symbol) |
| Headline | "Something went wrong" |
| Korean | "문제가 발생했습니다" |
| Body | "Our servers are having trouble. Please try again in a few minutes." |
| Korean Body | "서버에 문제가 발생했습니다. 잠시 후 다시 시도해 주세요." |
| Primary Action | "Retry" / "다시 시도" |
| Secondary Action | "Contact Support" / "문의하기" |

#### Timeout Error
| Element | Content |
|---------|---------|
| Icon | `schedule` (Material Symbol) |
| Headline | "Request timed out" |
| Korean | "요청 시간이 초과되었습니다" |
| Body | "The server is taking too long to respond. Please try again." |
| Korean Body | "서버 응답이 너무 오래 걸립니다. 다시 시도해 주세요." |
| Primary Action | "Retry" / "다시 시도" |

### Upload Errors (US-002)

#### File Too Large
| Element | Content |
|---------|---------|
| Inline Error | Icon + text below file picker |
| Message | "Video file too large. Please upload a file under 500MB." |
| Korean | "영상 파일이 너무 큽니다. 500MB 이하의 파일을 업로드해 주세요." |
| Guidance | "Current file: 650MB" |

#### Invalid Duration
| Element | Content |
|---------|---------|
| Message | "Video must be between 1 and 3 minutes." |
| Korean | "영상 길이는 1분에서 3분 사이여야 합니다." |
| Guidance | "Current duration: 5 minutes 30 seconds" |

#### Unsupported Format
| Element | Content |
|---------|---------|
| Message | "Unsupported format. Please upload MP4, MOV, or WebM." |
| Korean 

…(truncated)…
```

### UI_STATES > Validation

```text
### Form Field Validation (US-004)

#### Height Input
| State | Visual | Message |
|-------|--------|---------|
| Empty (required) | Red border, error icon | "Height is required" / "키를 입력해 주세요" |
| Below minimum | Red border, error icon | "Height must be at least 100cm" / "키는 100cm 이상이어야 합니다" |
| Above maximum | Red border, error icon | "Height must be under 250cm" / "키는 250cm 이하여야 합니다" |
| Invalid format | Red border, error icon | "Please enter a valid number" / "올바른 숫자를 입력해 주세요" |
| Valid | Green checkmark (optional) | Helper text or none |

#### Weight Input
| State | Visual | Message |
|-------|--------|---------|
| Empty (required) | Red border, error icon | "Weight is required" / "체중을 입력해 주세요" |
| Below minimum | Red border, error icon | "Weight must be at least 30kg" / "체중은 30kg 이상이어야 합니다" |
| Above maximum | Red border, error icon | "Weight must be under 200kg" / "체중은 200kg 이하여야 합니다" |
| Invalid format | Red border, error icon | "Please enter a valid number" / "올바른 숫자를 입력해 주세요" |
| Valid | Green checkmark (optional) | Helper text or none |

#### Experience Level Selection
| State | Visual | Message |
|-------|--------|---------|
| Not selected (required) | Red outline on selection group | "Please select your experience level" / "경력을 선택해 주세요" |
| Selected | Primary color highlight | None |

#### Stance Selection
| State | Visual | Message |
|-------|--------|---------|
| Not selected (required) | Red outline on selection group | "Please select your stance" / "스탠스를 선택해 주세요" |
| Selected | Primary color highlight | None |

### Validation Behavior
| Trigger | Behavior |
|---------|----------|
| On blur | Validate field when user leaves it |
| On change | Clear error when user starts correcting |
| On submit | Validate all fields; focus first erro

…(truncated)…
```

### UI_STATES > Success

```text
### Upload Success (US-002)
| Element | Content |
|---------|---------|
| Indicator | Green checkmark animation |
| Message | "Video uploaded successfully" |
| Korean | "영상이 업로드되었습니다" |
| Duration | Display for 2 seconds, then auto-navigate |
| Navigation | Automatically proceed to subject selection |

### Subject Selection Success (US-003)
| Element | Content |
|---------|---------|
| Indicator | Selected thumbnail with checkmark overlay |
| Visual | Blue selection ring around chosen subject |
| Confirmation | Enlarged preview of selected subject |
| Action | "Confirm Selection" button enabled |

### Body Spec Submission Success (US-004)
| Element | Content |
|---------|---------|
| Indicator | Form fields lock with subtle animation |
| Message | "Starting analysis..." |
| Korean | "분석을 시작합니다..." |
| Navigation | Proceed to processing status screen |

### Processing Complete Success (US-005/US-006/US-007)
| Element | Content |
|---------|---------|
| Indicator | Green checkmark with confetti animation (subtle) |
| Headline | "Analysis complete!" |
| Korean | "분석이 완료되었습니다!" |
| Body | "Your coaching report is ready to view" |
| Korean Body | "코칭 리포트가 준비되었습니다" |
| Primary Action | "View Report" / "리포트 보기" |
| Duration | Display until user action |

```
+------------------------------------------+
|            [checkmark-icon]              |
|                                          |
|        Analysis complete!                |
|                                          |
|  Your coaching report is ready to view   |
|                                          |
|         [View Report]                    |
+------------------------------------------+
```

### Share Link Created Success (US-009)
| Element | Content |
|---------|---------|
| Component | 

…(truncated)…
```

## Copy

### COPY > Tone & voice

```text
### Brand Voice Attributes

| Attribute | Description | Example |
|-----------|-------------|---------|
| Expert | Knowledgeable about boxing, not condescending | "Your guard recovery speed of 0.4s is above average" |
| Encouraging | Supportive of improvement journey | "You're showing strong fundamentals in..." |
| Direct | Clear, actionable feedback | "Focus on keeping your chin tucked during jabs" |
| Professional | Serious about the craft | "Analysis based on 127 detected movements" |

### Writing Principles

1. **Be concise**: Mobile-first means every word counts
2. **Be specific**: "Your left hook was 15% faster than average" not "Good punch"
3. **Be actionable**: Every weakness pairs with a recommendation
4. **Be respectful**: User is investing time in self-improvement

### Korean Localization Notes

- Use formal polite speech level (합쇼체/하십시오체) for system messages
- Use informal polite (해요체) for friendly UI prompts
- Boxing terminology follows Korean Boxing Commission standards
- Metric units always (cm, kg) - no conversion needed for Korean market

---
```

### COPY > UI copy

```text
### Landing Page

| Element | English | Korean |
|---------|---------|--------|
| Hero Headline | Get AI-Powered Boxing Analysis | AI 복싱 분석을 받아보세요 |
| Hero Subheadline | National-team level coaching feedback from your sparring videos | 스파링 영상으로 국가대표급 코칭 피드백을 받으세요 |
| CTA Primary | Get Started | 시작하기 |
| Feature 1 Title | Smart Movement Tracking | 스마트 동작 추적 |
| Feature 1 Desc | Advanced pose estimation analyzes every punch, guard, and movement | 첨단 포즈 추정 기술로 모든 펀치, 가드, 움직임을 분석합니다 |
| Feature 2 Title | Strategic Insights | 전략적 인사이트 |
| Feature 2 Desc | AI-generated analysis of your strengths, weaknesses, and improvement areas | AI가 생성한 강점, 약점, 개선점 분석을 제공합니다 |
| Feature 3 Title | Easy Sharing | 간편한 공유 |
| Feature 3 Desc | Share your analysis with coaches and training partners via unique links | 고유 링크로 코치와 훈련 파트너에게 분석을 공유하세요 |

### Login Page

| Element | English | Korean |
|---------|---------|--------|
| Page Title | Welcome to PunchAnalytics | PunchAnalytics에 오신 것을 환영합니다 |
| Subtitle | Sign in to continue | 계속하려면 로그인하세요 |
| Kakao Button | Continue with Kakao | 카카오로 계속하기 |
| Google Button | Continue with Google | Google로 계속하기 |
| Divider | or | 또는 |
| Privacy Link | Privacy Policy | 개인정보처리방침 |
| Terms Link | Terms of Service | 이용약관 |

### Dashboard

| Element | English | Korean |
|---------|---------|--------|
| Page Title | My Reports | 내 리포트 |
| Upload Button | Upload Video | 영상 업로드 |
| Empty State Headline | No analysis reports yet | 아직 분석 리포트가 없습니다 |
| Empty State Body | Upload your first sparring video to get AI-powered coaching feedback | 첫 번째 스파링 영상을 업로드하고 AI 코칭 피드백을 받아보세요 |
| Report Card Date | Analyzed on {date} | {date} 분석 |
| Report Card Summary | {count} key moments detected | {count}개의 주요 순간 감지됨 |
| Delete Button | Delete | 삭제 |
| Delete C

…(truncated)…
```

### COPY > Error messages

```text
### Upload Errors

| Error Code | English | Korean |
|------------|---------|--------|
| FILE_TOO_LARGE | Video file too large. Please upload a file under 500MB. | 영상 파일이 너무 큽니다. 500MB 이하의 파일을 업로드해 주세요. |
| INVALID_DURATION_SHORT | Video must be at least 1 minute long. | 영상 길이는 1분 이상이어야 합니다. |
| INVALID_DURATION_LONG | Video must be under 3 minutes. | 영상 길이는 3분 이하여야 합니다. |
| UNSUPPORTED_FORMAT | Unsupported format. Please upload MP4, MOV, or WebM. | 지원하지 않는 형식입니다. MP4, MOV 또는 WebM 파일을 업로드해 주세요. |
| UPLOAD_FAILED | Upload failed. Please try again. | 업로드에 실패했습니다. 다시 시도해 주세요. |
| UPLOAD_CANCELLED | Upload cancelled. | 업로드가 취소되었습니다. |

### Processing Errors

| Error Code | English | Korean |
|------------|---------|--------|
| POSE_ESTIMATION_FAILED | Unable to track subject clearly. Please upload video with better lighting or camera angle. | 대상을 명확하게 추적할 수 없습니다. 조명이나 카메라 각도가 더 좋은 영상을 업로드해 주세요. |
| NO_SUBJECTS_DETECTED | No subjects detected in video. Please upload a video with visible people. | 영상에서 사람을 감지할 수 없습니다. 사람이 보이는 영상을 업로드해 주세요. |
| ANALYSIS_FAILED | Analysis could not be completed. Please try again. | 분석을 완료할 수 없습니다. 다시 시도해 주세요. |
| ANALYSIS_TIMEOUT | Analysis is taking longer than expected. Please wait or try again later. | 분석이 예상보다 오래 걸리고 있습니다. 잠시 기다리거나 나중에 다시 시도해 주세요. |

### Authentication Errors

| Error Code | English | Korean |
|------------|---------|--------|
| LOGIN_FAILED | Login failed. Please try again or use a different login method. | 로그인에 실패했습니다. 다시 시도하거나 다른 로그인 방법을 사용해 주세요. |
| LOGIN_CANCELLED | Login cancelled. | 로그인이 취소되었습니다. |
| SESSION_EXPIRED | Your session has expired. Please log in again. | 세션이 만료되었습니다. 다시 로그인해 주세요. |
| UNAUTHORIZED | You need to log in to access this page. | 이 페이지에 접근하려면 로그인이 필요합니다. |

### Network Errors

…(truncated)…
```

## Design tokens

### DESIGN_SYSTEM > Design tokens

```text
All tokens are defined in the companion `design_tokens.json` file. This section explains the semantic mapping.

### Token Categories
| Category | Purpose | JSON Path |
|----------|---------|-----------|
| Colors | Brand and functional colors | `colors.*` |
| Typography | Font families, sizes, weights | `typography.*` |
| Spacing | Layout and component spacing | `spacing.*` |
| Radius | Border radius values | `radius.*` |
| Elevation | Shadow definitions | `elevation.*` |
| Motion | Animation timing | `motion.*` |

### Referencing Tokens
- Engineers should import `design_tokens.json` directly
- CSS custom properties follow pattern: `--pa-{category}-{name}`
- Example: `--pa-color-primary` maps to `colors.primary`

---
```

### DESIGN_SYSTEM > Color roles

```text
### Primary Palette
| Role | Usage | Light | Dark |
|------|-------|-------|------|
| Primary | CTAs, key actions, active states | #1565C0 | #A8C7FA |
| On Primary | Text/icons on primary | #FFFFFF | #062E6F |
| Primary Container | Selected states, chips | #D1E4FF | #1A4175 |

### Secondary Palette
| Role | Usage | Light | Dark |
|------|-------|-------|------|
| Secondary | Less prominent actions | #625B71 | #CCC2DC |
| Secondary Container | Supporting UI elements | #E8DEF8 | #4A4458 |

### Surface Palette
| Role | Usage | Light | Dark |
|------|-------|-------|------|
| Surface | Page backgrounds | #FEFBFF | #1C1B1F |
| Surface Variant | Card backgrounds | #E7E0EC | #49454F |
| On Surface | Primary text | #1C1B1F | #E6E1E5 |
| On Surface Variant | Secondary text | #49454F | #CAC4D0 |

### Feedback Colors
| Role | Usage | Light | Dark |
|------|-------|-------|------|
| Error | Validation errors | #B3261E | #F2B8B5 |
| Error Container | Error backgrounds | #F9DEDC | #8C1D18 |
| Success | Completion states | #2E7D32 | #81C784 |
| Warning | Caution states | #ED6C02 | #FFB74D |
| Info | Informational | #0288D1 | #4FC3F7 |

### Boxing-Specific Colors
| Role | Usage | Hex |
|------|-------|-----|
| Strike | Punch visualization | #E53935 |
| Defense | Guard visualization | #1976D2 |
| Movement | Footwork visualization | #7B1FA2 |
| Strength | Positive metrics | #2E7D32 |
| Weakness | Improvement areas | #ED6C02 |

---
```

## Open questions

### UX_SPEC > Open questions

```text
### Resolved Decisions

| Question | Decision | Rationale |
|----------|----------|-----------|
| Support video trimming in-app? | No | Out of scope for MVP; reduces complexity |
| Maximum video duration? | 3 minutes | Balances processing cost and user need |
| Maximum file size? | 500MB | Supports HD video for 3 minutes |
| Email verification required? | No | Reduce friction; OAuth provides verified email |

### Deferred to Post-Launch

| Question | Deferral Reason | Impact |
|----------|-----------------|--------|
| Should we add video preview before upload confirmation? | Adds complexity; not critical for MVP | Minor UX improvement |
| Should processing notification be push or in-app? | Push notifications require additional infrastructure | Users must check app for status |
| Should we show pose skeleton overlay on report? | P1 feature (US-011) | Report shows text-only analysis |
| Should we support batch uploads? | Low priority; single video flow sufficient | Users upload one at a time |
```

### UX_REPORT > Open questions

```text
### Resolved During Design

| Question | Resolution |
|----------|------------|
| Video trimming in-app? | No - out of scope for MVP; users trim before upload |
| Email verification required? | No - OAuth provides verified email; reduce friction |
| Maximum video duration? | 3 minutes - balances processing cost and user need |
| Maximum file size? | 500MB - supports HD video for 3 minutes |

### Deferred to Implementation

| Question | Impact | Decision Deadline |
|----------|--------|-------------------|
| Exact frame extraction interval for thumbnails | Affects subject selection quality | Before US-003 implementation |
| Specific LLM prompt structure | Affects analysis quality | Before US-007 implementation |
| Retry count and backoff timing for LLM failures | Affects user wait experience | Before US-007 implementation |
| Soft delete retention period for reports | Affects storage costs | Before US-010 implementation |

### Requires Domain Expert Input

| Question | Why It Matters | Owner |
|----------|---------------|-------|
| Boxing terminology localization accuracy | Korean boxing terms must be correct | Product + Korean Boxing Expert |
| Metric threshold definitions (what is "good" reach ratio?) | Analysis credibility | Product + Boxing Coach |
| Typical amateur boxer video conditions | Affects pose estimation guidance | Engineering + User Research |

### Post-Launch Evaluation

| Question | Success Metric | Timeline |
|----------|---------------|----------|
| Is 5-minute processing acceptable to users? | Drop-off rate during processing < 10% | 30 days post-launch |
| Do users understand subject selection? | Selection success rate > 95% | 30 days post-launch |
| Is Korean copy natural to native speakers? | User feedback, NPS by language | 60 d

…(truncated)…
```

---

## Source references

- docs/ux/UX_CONTRACT.md
- docs/ux/UX_SPEC.md
- docs/ux/IA_MAP.md
- docs/ux/UI_STATES.md
- docs/ux/COPY.md
- docs/ux/DESIGN_SYSTEM.md
- docs/ux/UX_REPORT.md
